/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe — returns 200 without touching any backing service.
         *
         *     Intentionally at root (no /v1 prefix): the compose/nginx healthcheck probes
         *     `http://localhost:8000/health` directly, bypassing nginx (ADR-007 §4).
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness: 200 when DB+Redis+Celery reachable, else 503 with per-dep markers.
         *
         *     HEAD is registered explicitly (FastAPI does not auto-derive it from GET) —
         *     uptime monitors (UptimeRobot) probe with HEAD and treated the 405 as DOWN.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Account
         * @description Delete the authenticated user and all their data (cascade) -> 204.
         */
        delete: operations["delete_account_v1_account_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Alerts
         * @description List the caller's alerts with cursor pagination and plan-based history window.
         *
         *     Free plan → returns empty list + history_unavailable=True (not 403).
         *     Pro/Team → returns alerts within the plan's history window (30/90 days).
         *     Always tenant-scoped: only the caller's alerts are returned.
         *     Pass `cursor` from the previous response's `next_cursor` field to load the next page.
         *     Invalid cursor → 422.
         */
        get: operations["list_alerts_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Alert
         * @description Get one alert detail. Foreign or missing alert → 404 (no existence leak).
         */
        get: operations["get_alert_v1_alerts__alert_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Api Keys
         * @description List all API keys for the caller (masked: prefix/name/timestamps, no key/key_hash).
         */
        get: operations["list_api_keys_v1_api_keys_get"];
        put?: never;
        /**
         * Create Api Key
         * @description Issue a new API key for the caller (Team plan only).
         *
         *     Free/Pro → PlanLimitExceeded → 403 (via api/main.py exception handler).
         *     Plaintext key is returned ONCE in the response body and never stored in DB.
         */
        post: operations["create_api_key_v1_api_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api-keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke Api Key
         * @description Soft-revoke an API key owned by the caller.
         *
         *     Unknown id or another tenant's id → 404 (no existence leak, ADR-002).
         *     The key_hash row is kept for audit; revoked_at marks it inactive.
         */
        delete: operations["revoke_api_key_v1_api_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset:Forgot Password */
        post: operations["reset_forgot_password_v1_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/google/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oauth:Google.Jwt.Authorize */
        get: operations["oauth_google_jwt_authorize_v1_auth_google_authorize_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Oauth:Google.Jwt.Callback
         * @description The response varies based on the authentication backend used.
         */
        get: operations["oauth_google_jwt_callback_v1_auth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/jwt/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth:Jwt.Login */
        post: operations["auth_jwt_login_v1_auth_jwt_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/jwt/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth:Jwt.Logout */
        post: operations["auth_jwt_logout_v1_auth_jwt_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register:Register */
        post: operations["register_register_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/request-verify-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify:Request-Token */
        post: operations["verify_request_token_v1_auth_request_verify_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset:Reset Password */
        post: operations["reset_reset_password_v1_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify:Verify */
        post: operations["verify_verify_v1_auth_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/invoice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Invoice
         * @description Create a NOWPayments invoice for the caller's chosen plan/period.
         */
        post: operations["create_invoice_v1_billing_invoice_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/ipn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive Ipn
         * @description Receive a NOWPayments IPN: verify HMAC over the RAW body, then apply.
         */
        post: operations["receive_ipn_v1_billing_ipn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cases
         * @description Return top proof-of-speed cases sorted by lead-time DESC.
         *
         *     Public endpoint: no authentication required.
         *
         *     Only cases where the operator has set ``mainstream_at`` are returned
         *     — cases without a mainstream timestamp are not yet proof-points.
         *
         *     Query params:
         *         top_n: Max items to return.  Defaults to settings.cases_top_n_max.
         *                422 if top_n exceeds settings.cases_top_n_max.
         *
         *     Response sorted by ``lead_time_seconds`` (= mainstream_at - first_seen) DESC.
         */
        get: operations["get_cases_v1_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/email/unsubscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Unsubscribe
         * @description Verify the signed token and idempotently opt the user out.
         *
         *     Returns:
         *         200: HTML confirmation (also on repeat clicks and deleted users —
         *              idempotent, no enumeration).
         *         400: Unified error-envelope for ANY invalid/expired/tampered token.
         */
        get: operations["unsubscribe_v1_email_unsubscribe_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feedback/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Record Feedback
         * @description Verify signed token, UPSERT alert_feedback, return HTML 'спасибо'.
         *
         *     Rate-limited at ``feedback_rate_limit_per_minute`` (default 30/min,
         *     per-IP via ``rate_limit_key``).
         *
         *     Returns:
         *         200: Feedback recorded (or idempotent re-tap).
         *         400: Invalid/tampered/expired token (uniform — no oracle).
         *         404: Alert not found (FK gone — likely deleted by retention).
         *         410: Same as 404 but signals the resource is intentionally gone.
         */
        get: operations["record_feedback_v1_feedback__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/business-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Business metrics snapshot (superuser only)
         * @description Return an aggregate business metrics snapshot.
         *
         *     Auth:
         *     - 401 if no valid session cookie.
         *     - 403 if authenticated but not a superuser.
         *     - 200 with JSON body for a superuser.
         *
         *     All values are global aggregates; no per-user identifiers are included.
         */
        get: operations["get_business_metrics_v1_ops_business_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Packs
         * @description Return the full curated pack catalog (auth required — AC1).
         *
         *     No DB query: the catalog is a static in-memory structure. Auth is required
         *     so unauthenticated crawlers cannot enumerate the catalog.
         */
        get: operations["get_packs_v1_packs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/packs/{slug}/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Subscribe Pack
         * @description Subscribe to a curated pack — creates watchlist rows with pack_slug marker.
         *
         *     - 404 if slug not in catalog.
         *     - 402 if the user has reached their PACKS plan limit (handled globally).
         *     - Idempotent: re-subscribing the same pack returns created=0, not an error.
         *     - Skip-conflicts (channel already watched manually) are counted in `skipped`.
         */
        post: operations["subscribe_pack_v1_packs__slug__subscribe_post"];
        /**
         * Unsubscribe Pack
         * @description Unsubscribe from a pack — deletes all watchlist rows with this pack_slug.
         *
         *     - 404 if slug not in catalog (unknown pack — not just "not subscribed").
         *     - 200 with deleted=0 if the slug is valid but the user is not subscribed.
         *     - Manual watchlists (pack_slug IS NULL) are NEVER touched.
         */
        delete: operations["unsubscribe_pack_v1_packs__slug__subscribe_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pool-admin/pool-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest pool-health snapshot (superuser only)
         * @description Read the latest `pool:health:latest` snapshot from Redis.
         *
         *     Missing/old snapshot (collector down ≥ TTL, or lagging) → `stale=true` with
         *     empty aggregates. Redis unreachable → 503 envelope (not an unhandled 500).
         *     A parse/validation failure of a present snapshot is treated as stale.
         */
        get: operations["get_pool_health_v1_pool_admin_pool_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pool-admin/qr-login/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Begin a QR login (superuser only)
         * @description Start a QR login and return the deep link + token.
         *
         *     Auth: 401 unauthenticated, 403 non-superuser. Maps service raise-paths:
         *     missing creds → 503, registry at capacity → 429. No secrets logged.
         */
        post: operations["start_qr_login_v1_pool_admin_qr_login_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pool-admin/qr-login/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll a QR login (superuser only)
         * @description Poll an in-progress login; on SUCCESS persist + classify (TASK-119/120).
         *
         *     Reflects `service.poll()`: unknown/expired tokens return status `expired`
         *     (200, never 404/500 — the UI polls in a loop). On SUCCESS the body carries the
         *     minted `session_string` (secret, never logged) AND, when the poll yields an
         *     account identity, the route PERSISTS the session via the dynamic store
         *     (`upsert_revive_or_add`, idempotent by `tg_user_id`), writes the NON-SECRET
         *     revive-signal on a REVIVE so the worker swaps the live slot, and returns the
         *     non-secret identity + outcome ("revive"/"add").
         *
         *     A persistence/DB failure does NOT drop the minted `session_string`: it is still
         *     returned as the disaster-recovery floor (the admin can paste it into the vault),
         *     and the failure surfaces as a clear envelope only when the pool is over capacity.
         */
        get: operations["poll_qr_login_v1_pool_admin_qr_login__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/referral/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Referral Me
         * @description Return the authenticated user's referral code, share link, and earned rewards.
         *
         *     The ref_code is generated lazily on first call and cached on the user row.
         *     Only rewards where referrer_id == current_user.id are returned.
         */
        get: operations["get_referral_me_v1_referral_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trending
         * @description Return the top trending clusters for a pack (showcase tenant, 24h window).
         *
         *     No plan gate: Free users see /trending after registration (Decision §Discussion).
         *     This is showcase data (our own), not the user's personal history.
         *
         *     pack:  Required. Pack slug from the catalog. 404 if unknown.
         *     limit: Optional. Must be ≤ settings.trending_top_k_max (422 otherwise).
         *            Defaults to settings.trending_top_k_default.
         *
         *     Response includes warming_up=true when the showcase tenant is not yet warmed up
         *     (fresh deploy); the frontend should display «собираем сигналы…» in that case.
         */
        get: operations["get_trending_v1_trending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Users Me
         * @description Return the authenticated user's profile.
         *
         *     Behind `current_user` dependency: returns 401 without a valid auth cookie.
         *     Tenant-scoped: only reads data belonging to the requesting user.
         */
        get: operations["get_users_me_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me/delivery-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Delivery Config
         * @description Return the authenticated user's delivery configuration (token masked).
         *
         *     `telegram_bot_token` is never returned as the full value — only a masked
         *     representation showing the last 4 characters (or None if not set).
         *     Tenant-scoped: reads only `current_user` data.
         */
        get: operations["get_delivery_config_v1_users_me_delivery_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Delivery Config
         * @description Partial-update the authenticated user's delivery configuration.
         *
         *     - `webhook_url`: requires Pro+ plan (feature-gate → 403 on Free);
         *       SSRF-validated via task-009 guard (private/localhost/non-https → 422).
         *     - `telegram_bot_token`/`telegram_chat_id`: available on all plans.
         *     - Only provided fields are updated (partial PATCH semantics).
         *     - Returns the updated config with the bot token masked.
         */
        patch: operations["patch_delivery_config_v1_users_me_delivery_config_patch"];
        trace?: never;
    };
    "/v1/users/me/tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read My Tenant
         * @description Protected example route (AC2): 401 without a token, tenant id with one.
         */
        get: operations["read_my_tenant_v1_users_me_tenant_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/watchlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Watchlists
         * @description List only the caller's watchlists (tenant-scoped).
         *
         *     Accepts cookie/JWT (UI) or X-API-Key header (programmatic, TASK-028).
         */
        get: operations["list_watchlists_v1_watchlists_get"];
        put?: never;
        /**
         * Create Watchlist
         * @description Create one watchlist (single channel) for the caller -> 201 WatchlistRead.
         */
        post: operations["create_watchlist_v1_watchlists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/watchlists/{watchlist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Watchlist
         * @description Get one owned watchlist; missing / other tenant's id -> 404.
         */
        get: operations["get_watchlist_v1_watchlists__watchlist_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Watchlist
         * @description Delete an owned watchlist; missing / other tenant's id -> 404.
         */
        delete: operations["delete_watchlist_v1_watchlists__watchlist_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Watchlist
         * @description Partial update of an owned watchlist; missing / other tenant's id -> 404.
         */
        patch: operations["update_watchlist_v1_watchlists__watchlist_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlertConfig
         * @description Per-watchlist alert tuning (maps to Watchlist.threshold/min_channels/lang).
         */
        AlertConfig: {
            /** Min Channels */
            min_channels: number;
            /**
             * Notification Lang
             * @default en
             */
            notification_lang: string;
            /** Score Threshold */
            score_threshold: number;
        };
        /**
         * AlertListResponse
         * @description Cursor-paginated list response envelope for GET /alerts (TASK-020).
         *
         *     `next_cursor` is an opaque base64url token encoding (first_seen, id) for the
         *     keyset position. None means no more pages. Clients MUST treat it as opaque
         *     and pass it back verbatim via the `cursor` query parameter.
         *
         *     `history_unavailable` is True when the caller's plan has no history window
         *     (Free plan, HISTORY == 0). The UI must show the plan-upgrade upsell.
         *     The plan window is enforced backend-side; the frontend MUST NOT hard-code
         *     the 30/90 day numbers inline (TASK-016 invariant: backend is source of truth).
         */
        AlertListResponse: {
            /** History Unavailable */
            history_unavailable: boolean;
            /** Items */
            items: components["schemas"]["AlertRead"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * AlertRead
         * @description Read-only projection of one alert row (with Cluster.topic join).
         *
         *     Feedback fields (`feedback`, `feedback_token_up`, `feedback_token_down`) are
         *     populated ONLY in the detail endpoint (`get_alert`). The list endpoint
         *     (`list_alerts`) leaves them at their `None` default — per-item feedback tokens
         *     are not minted for a 20-row page (TASK-064 AC4). `feedback` is the caller's
         *     current verdict ("up" | "down" | null) read from `alert_feedback`; the two
         *     token fields are freshly-minted feedback tokens (reusable until TTL expiry —
         *     the write-path UPSERT is idempotent) for the web 👍/👎 buttons. They are None
         *     when token minting is unavailable (empty jwt_secret / mint failure — graceful
         *     degradation, the buttons are then hidden client-side).
         */
        AlertRead: {
            /** Channels Count */
            channels_count: number;
            /** Delivery Status */
            delivery_status: string;
            /** Feedback */
            feedback?: string | null;
            /** Feedback Token Down */
            feedback_token_down?: string | null;
            /** Feedback Token Up */
            feedback_token_up?: string | null;
            /**
             * First Seen
             * Format: date-time
             */
            first_seen: string;
            /** Id */
            id: number;
            /** Score */
            score: number;
            /** Topic */
            topic: string;
        };
        /**
         * ApiKeyCreate
         * @description Request body for POST /api-keys — only the human-readable name.
         */
        ApiKeyCreate: {
            /**
             * Name
             * @description Human-readable label for the key (e.g. 'prod-integration').
             */
            name: string;
        };
        /**
         * ApiKeyCreated
         * @description Response for POST /api-keys — includes the plaintext key EXACTLY ONCE.
         *
         *     The `key` field is the plaintext. After this response the plaintext is gone;
         *     it is not stored in the DB. The user must copy it immediately.
         */
        ApiKeyCreated: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Prefix */
            prefix: string;
        };
        /**
         * ApiKeyRead
         * @description Read-only view of an API key (list / detail) — NO plaintext or key_hash.
         *
         *     Exposes only the prefix (for recognition), name, and timestamps. Safe to
         *     return in list responses without exposing sensitive material.
         */
        ApiKeyRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Last Used At */
            last_used_at: string | null;
            /** Name */
            name: string;
            /** Prefix */
            prefix: string;
            /** Revoked At */
            revoked_at: string | null;
        };
        /**
         * BillingPeriod
         * @description Billing period for an invoice. Crypto has no native subscriptions — every
         *     period is a single prepaid invoice; durations live in `PERIOD_DAYS`.
         *
         *     TASK-047: `QUARTER` (-10%) and `YEAR` (-20%) extend the grid; prices are
         *     explicit constants in `PLAN_PERIOD_PRICES_USD`, never runtime discount math.
         * @enum {string}
         */
        BillingPeriod: "month" | "quarter" | "year";
        /** Body_auth_jwt_login_v1_auth_jwt_login_post */
        Body_auth_jwt_login_v1_auth_jwt_login_post: {
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
            /** Grant Type */
            grant_type?: string | null;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Username */
            username: string;
        };
        /** Body_reset_forgot_password_v1_auth_forgot_password_post */
        Body_reset_forgot_password_v1_auth_forgot_password_post: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** Body_reset_reset_password_v1_auth_reset_password_post */
        Body_reset_reset_password_v1_auth_reset_password_post: {
            /** Password */
            password: string;
            /** Token */
            token: string;
        };
        /** Body_verify_request_token_v1_auth_request_verify_token_post */
        Body_verify_request_token_v1_auth_request_verify_token_post: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** Body_verify_verify_v1_auth_verify_post */
        Body_verify_verify_v1_auth_verify_post: {
            /** Token */
            token: string;
        };
        /**
         * BusinessMetricsResponse
         * @description Aggregate business metrics response (no per-user data, extra='forbid').
         *
         *     All fields are global aggregates; no `email`, `user_id`, or other PII.
         *     `extra='forbid'` means an accidental per-user field would raise at response
         *     validation time, making the invariant structurally enforced.
         */
        BusinessMetricsResponse: {
            /** Active Subscriptions By Plan */
            active_subscriptions_by_plan: {
                [key: string]: number;
            };
            /** Avg Check 30D */
            avg_check_30d: string;
            funnel_last_30d: components["schemas"]["FunnelSummary"];
            /** Mrr */
            mrr: string;
            /** Repeat Payment Rate */
            repeat_payment_rate: number | null;
        };
        /**
         * CaseItem
         * @description Aggregate projection of one proof-of-speed case — aggregate fields only.
         *
         *     Fields:
         *         title:              Sanitized display label (sanitize_topic_label applied).
         *         viral_score:        Composite virality score at fixation time.
         *         first_seen:         UTC timestamp when the cluster was first detected.
         *         mainstream_at:      UTC timestamp when the topic appeared in mainstream media
         *                             (operator-filled). Always NOT NULL in responses (cases
         *                             without mainstream_at are hidden from this endpoint).
         *         lead_time_seconds:  Computed: (mainstream_at - first_seen) in whole seconds.
         *                             Positive means we detected the trend before mainstream media.
         *         channels_count:     Number of source channels in the cluster at fixation
         *                             time (real count from scores.channels_count).
         *
         *     Deliberately absent (security §5.5 / compliance §7):
         *         - id (internal PK — not exposed)
         *         - raw topic text, post content, channel handles, URLs
         *         - created_at (internal audit field)
         */
        CaseItem: {
            /** Channels Count */
            channels_count: number;
            /**
             * First Seen
             * Format: date-time
             */
            first_seen: string;
            /** Lead Time Seconds */
            lead_time_seconds: number;
            /**
             * Mainstream At
             * Format: date-time
             */
            mainstream_at: string;
            /** Title */
            title: string;
            /** Viral Score */
            viral_score: number;
        };
        /**
         * CasesResponse
         * @description Response envelope for GET /cases.
         */
        CasesResponse: {
            /** Items */
            items: components["schemas"]["CaseItem"][];
        };
        /**
         * ChannelRef
         * @description A single source reference: a platform `kind` + its `handle` (ADR-001).
         */
        ChannelRef: {
            /** Handle */
            handle: string;
            /** @default telegram */
            kind: components["schemas"]["SourceKind"];
        };
        /**
         * DeliveryConfigRead
         * @description Read projection of the user's delivery configuration.
         *
         *     `telegram_bot_token_masked` is None if not set, or a masked string
         *     (e.g. ``***gh1``) if set. The full token is NEVER included.
         */
        DeliveryConfigRead: {
            /** Telegram Bot Token Masked */
            telegram_bot_token_masked: string | null;
            /** Telegram Chat Id */
            telegram_chat_id: string | null;
            /** Webhook Url */
            webhook_url: string | null;
        };
        /**
         * DeliveryConfigUpdate
         * @description Partial-update body for PATCH /users/me/delivery-config.
         *
         *     All fields are optional; only provided fields are updated.
         *     `webhook_url` must pass the server-side SSRF guard (task-009) and the
         *     Pro+ feature-gate check before persisting.
         */
        DeliveryConfigUpdate: {
            /** Telegram Bot Token */
            telegram_bot_token?: string | null;
            /** Telegram Chat Id */
            telegram_chat_id?: string | null;
            /** Webhook Url */
            webhook_url?: string | null;
        };
        /** ErrorModel */
        ErrorModel: {
            /** Detail */
            detail: string | {
                [key: string]: string;
            };
        };
        /**
         * FunnelDayRow
         * @description One UTC calendar day's funnel counters (from business_metrics_daily).
         */
        FunnelDayRow: {
            /** Active Paid */
            active_paid: number;
            /** Churned */
            churned: number;
            /**
             * Day
             * Format: date
             */
            day: string;
            /** First Alerts Delivered */
            first_alerts_delivered: number;
            /** First Feedback */
            first_feedback: number;
            /** New Paid */
            new_paid: number;
            /** Packs Attached */
            packs_attached: number;
            /** Registrations */
            registrations: number;
        };
        /**
         * FunnelSummary
         * @description 30-day funnel window with daily rows + summary conversion rate.
         */
        FunnelSummary: {
            /** Conversion Free To Paid */
            conversion_free_to_paid: number;
            /** Daily */
            daily: components["schemas"]["FunnelDayRow"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness payload returned by `GET /health`.
         */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * InvoiceRequest
         * @description Create-invoice request body (validated at the boundary).
         */
        InvoiceRequest: {
            /** @default month */
            period: components["schemas"]["BillingPeriod"];
            plan: components["schemas"]["Plan"];
        };
        /**
         * InvoiceResponse
         * @description Invoice response: where to pay + the order id to reconcile the IPN.
         */
        InvoiceResponse: {
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
            /** Order Id */
            order_id: string;
            /** Payment Url */
            payment_url: string;
            /** Redirect Url */
            redirect_url: string | null;
        };
        /**
         * IpnAck
         * @description Ack body returned for any handled IPN (200).
         */
        IpnAck: {
            /** Status */
            status: string;
        };
        /** OAuth2AuthorizeResponse */
        OAuth2AuthorizeResponse: {
            /** Authorization Url */
            authorization_url: string;
        };
        /**
         * PackRead
         * @description Catalog entry returned by GET /packs.
         */
        PackRead: {
            /** Channels Count */
            channels_count: number;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Topic */
            topic: string;
        };
        /**
         * Plan
         * @description Subscription tiers (overview §6). String values match `users.plan`.
         * @enum {string}
         */
        Plan: "free" | "pro" | "team";
        /**
         * PoolHealthAccount
         * @description One pool account's health, with optional NON-SECRET identity (TASK-120).
         *
         *     `index` is the stable per-slot identifier; `display_label`/`tg_user_id` are the
         *     NON-SECRET store identity (masked id / `@username` / numeric id) when the slot was
         *     loaded from the dynamic store, else null (an env-only slot). NEVER a session string.
         */
        PoolHealthAccount: {
            /** Cooldown Remaining Seconds */
            cooldown_remaining_seconds?: number | null;
            /** Display Label */
            display_label?: string | null;
            /** Index */
            index: number;
            /**
             * Last Error Reason
             * @default
             */
            last_error_reason: string;
            /**
             * Read Failure Count
             * @default 0
             */
            read_failure_count: number;
            /**
             * Source
             * @default manual
             */
            source: string;
            /** State */
            state: string;
            /** Tg User Id */
            tg_user_id?: number | null;
        };
        /**
         * PoolHealthResponse
         * @description `GET /pool-admin/pool-health` body — aggregates + per-account list + staleness.
         *
         *     `stale` is true when the snapshot is missing/old (collector down or lagging);
         *     in that case the aggregates are zeroed and `accounts` is empty so the UI can
         *     say "no fresh data from collector" without erroring.
         */
        PoolHealthResponse: {
            /** Accounts */
            accounts?: components["schemas"]["PoolHealthAccount"][];
            /** As Of */
            as_of?: string | null;
            /**
             * Cooling
             * @default 0
             */
            cooling: number;
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /**
             * Healthy
             * @default 0
             */
            healthy: number;
            /**
             * Ingest Contradiction
             * @default false
             */
            ingest_contradiction: boolean;
            /**
             * Quarantined
             * @default 0
             */
            quarantined: number;
            /**
             * Size
             * @default 0
             */
            size: number;
            /**
             * Stale
             * @default true
             */
            stale: boolean;
            /**
             * Target
             * @default 0
             */
            target: number;
        };
        /**
         * QRLoginPollResponse
         * @description `GET /pool-admin/qr-login/{token}` body — the current login state.
         *
         *     `session_string` is the NEWLY minted StringSession, present ONLY on SUCCESS.
         *     It is a SECRET (the admin copies it to the vault); it is never logged and is
         *     served only to a superuser over HTTPS.
         */
        QRLoginPollResponse: {
            /** Display Label */
            display_label?: string | null;
            /** Expires At */
            expires_at: number;
            /** Outcome */
            outcome?: string | null;
            /** Reason */
            reason?: string | null;
            /** Session String */
            session_string?: string | null;
            /** Status */
            status: string;
            /** Tg User Id */
            tg_user_id?: number | null;
        };
        /**
         * QRLoginStartResponse
         * @description `POST /pool-admin/qr-login/start` body — the QR deep link + expiry.
         */
        QRLoginStartResponse: {
            /** Expires At */
            expires_at: number;
            /** Qr Url */
            qr_url: string;
            /** Timeout Seconds */
            timeout_seconds: number;
            /** Token */
            token: string;
        };
        /**
         * ReferralMeRead
         * @description Response schema for GET /referral/me.
         *
         *     ref_code: the authenticated user's unique share code (generated lazily).
         *     referral_link: full registration URL pre-filled with the ref code.
         *     rewards: list of reward rows earned by this user (pending and paid).
         */
        ReferralMeRead: {
            /** Ref Code */
            ref_code: string;
            /** Referral Link */
            referral_link: string;
            /** Rewards */
            rewards: components["schemas"]["ReferralRewardRead"][];
        };
        /**
         * ReferralRewardRead
         * @description One reward row as returned by GET /referral/me.
         */
        ReferralRewardRead: {
            /** Amount Usdt */
            amount_usdt: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Paid At */
            paid_at: string | null;
            /** Payment Id */
            payment_id: number | null;
            /** Referred User Id */
            referred_user_id: number | null;
            /** Referrer Id */
            referrer_id: number;
            /** Status */
            status: string;
        };
        /**
         * SourceKind
         * @description Platform a channel belongs to (ADR-001). Mirrors `collector.base.SourceKind`.
         *
         *     The `source_kind` column is `Enum(..., native_enum=False)` (VARCHAR(32), no DB
         *     CHECK constraint — see migration 0001), so adding a member needs NO migration.
         * @enum {string}
         */
        SourceKind: "telegram" | "twitter" | "reddit";
        /**
         * SubscribeResult
         * @description Result of POST /packs/{slug}/subscribe.
         */
        SubscribeResult: {
            /** Created */
            created: number;
            /** Skipped */
            skipped: number;
        };
        /**
         * TenantResponse
         * @description Tenant identity payload for the protected example route.
         */
        TenantResponse: {
            /** User Id */
            user_id: number;
        };
        /**
         * TrendingItem
         * @description Aggregate projection of one viral cluster — aggregate fields only.
         *
         *     Fields:
         *       topic:          Sanitized display label derived from the cluster centroid
         *                       (cluster.topic). URLs, @-handles, and email addresses are
         *                       stripped at the API boundary; length is capped to
         *                       TRENDING_LABEL_MAX_LEN (80) characters (compliance §7, AC5).
         *       viral_score:    Composite virality score (score.viral_score).
         *       channels_count: Real number of unique channels contributing to this cluster
         *                       at scoring time (scores.channels_count, persisted by the
         *                       scorer). Aggregate number only — no channel ids/handles.
         *       first_seen:     UTC timestamp when the cluster was first detected.
         *
         *     Deliberately absent (compliance §7):
         *       - post text, message content, channel handles, URLs, raw metadata.
         */
        TrendingItem: {
            /** Channels Count */
            channels_count: number;
            /**
             * First Seen
             * Format: date-time
             */
            first_seen: string;
            /** Topic */
            topic: string;
            /** Viral Score */
            viral_score: number;
        };
        /**
         * TrendingResponse
         * @description Response envelope for GET /trending.
         *
         *     warming_up semantics:
         *       True  — showcase tenant absent OR has no clusters at all (fresh deploy).
         *               Frontend shows «собираем сигналы…» state.
         *       False — showcase tenant exists AND has at least one cluster. The items list
         *               may still be empty (e.g. no activity for the requested pack in the
         *               last 24h) — this is honest data, not a warming-up state.
         */
        TrendingResponse: {
            /** Items */
            items: components["schemas"]["TrendingItem"][];
            /** Warming Up */
            warming_up: boolean;
        };
        /**
         * UnsubscribeResult
         * @description Result of DELETE /packs/{slug}/subscribe.
         */
        UnsubscribeResult: {
            /** Deleted */
            deleted: number;
        };
        /**
         * UserCreate
         * @description Registration payload (email + password + optional referrer_code).
         *
         *     referrer_code: optional referral code supplied by the inviting user.  Passed
         *     at registration to bind referred_by on the new user.  Invalid/unknown codes
         *     are silently ignored (registration always succeeds — INVARIANT: referral
         *     errors must not block register).  Max length validated here.
         *
         *     CRITICAL: the field is named 'referrer_code' (NOT 'ref_code') to avoid
         *     colliding with the User ORM column users.ref_code.  fastapi-users
         *     create_update_dict() passes the dict straight into User(**kwargs); if the
         *     field were named 'ref_code' it would overwrite the new user's own ref_code
         *     with the referrer's code string → UniqueViolation / pollution (TASK-046 G2).
         *
         *     create_update_dict() is overridden here to exclude 'referrer_code' from the
         *     INSERT dict entirely — the referral binding is handled separately by
         *     UserManager._bind_referral() via the raw request body.
         */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean | null;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean | null;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean | null;
            /** Password */
            password: string;
            /** Referrer Code */
            referrer_code?: string | null;
        };
        /**
         * UserMeResponse
         * @description Public current-user payload (read-only, no secrets).
         */
        UserMeResponse: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Id */
            id: number;
            /** Is Superuser */
            is_superuser: boolean;
            /** Is Verified */
            is_verified: boolean;
            /** Plan */
            plan: string;
        };
        /**
         * UserRead
         * @description Public user representation returned by register / users routes.
         */
        UserRead: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Id */
            id: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WatchlistCreate
         * @description Create payload: one topic + one channel + alert-config -> one watchlist row.
         */
        WatchlistCreate: {
            alert_config: components["schemas"]["AlertConfig"];
            channel: components["schemas"]["ChannelRef"];
            /** Topic */
            topic: string;
        };
        /**
         * WatchlistRead
         * @description Response model: the persisted watchlist row, tenant id included (AC1).
         *
         *     `signal` (TASK-096) carries the live virality signal for the row's channel —
         *     always present, graceful-empty when there is no data.
         */
        WatchlistRead: {
            alert_config: components["schemas"]["AlertConfig"];
            channel: components["schemas"]["ChannelRef"];
            /** Id */
            id: number;
            signal?: components["schemas"]["WatchlistSignal"];
            /** Topic */
            topic: string;
            /** User Id */
            user_id: number;
        };
        /**
         * WatchlistSignal
         * @description Live signal for a watchlist row on the Signal Desk (TASK-096).
         *
         *     Aggregated read-only from the `Score` / `Alert` rows of the clusters the
         *     watchlist's channel participates in (channel-overlap join, TASK-084). Every
         *     field is graceful: `None` / empty when there is genuinely no data — never
         *     fabricated (INV2).
         *
         *     - `live_velocity` — latest in-window `Score.velocity` (∈ [0, 1] normalized
         *       cross-channel burst), `None` when no in-window score.
         *     - `live_score` — latest in-window `Score.viral_score` (0-100), `None` when none.
         *     - `sparkline_24h` — hourly max `viral_score` over the last 24h, oldest→newest;
         *       empty when no in-window scores.
         *     - `last_alert_at` — most recent alert's `first_seen`, `None` when no alert.
         *     - `effective_sources` — `exp(source-entropy)` of the latest in-window score
         *       (TASK-126): the effective number of independent sources (single-source
         *       amplification collapses to ~1.0). An organic-spread / independence signal,
         *       NOT a coordination verdict; pair with synchrony/similarity-null next. `None`
         *       when there is no in-window score or the score predates the migration.
         */
        WatchlistSignal: {
            /** Effective Sources */
            effective_sources?: number | null;
            /** Last Alert At */
            last_alert_at?: string | null;
            /** Live Score */
            live_score?: number | null;
            /** Live Velocity */
            live_velocity?: number | null;
            /** Sparkline 24H */
            sparkline_24h?: number[];
        };
        /**
         * WatchlistUpdate
         * @description Partial update: only supplied fields are applied (PATCH, `exclude_unset`).
         */
        WatchlistUpdate: {
            alert_config?: components["schemas"]["AlertConfig"] | null;
            channel?: components["schemas"]["ChannelRef"] | null;
            /** Topic */
            topic?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    delete_account_v1_account_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_alerts_v1_alerts_get: {
        parameters: {
            query?: {
                /** @description Maximum number of alerts to return (server silently clamps to max). */
                limit?: number;
                /** @description Opaque pagination cursor from previous response next_cursor field. */
                cursor?: string | null;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alert_v1_alerts__alert_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_api_keys_v1_api_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyRead"][];
                };
            };
        };
    };
    create_api_key_v1_api_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_key_v1_api_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_forgot_password_v1_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_reset_forgot_password_v1_auth_forgot_password_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_google_jwt_authorize_v1_auth_google_authorize_get: {
        parameters: {
            query?: {
                scopes?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuth2AuthorizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_google_jwt_callback_v1_auth_google_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                code_verifier?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_jwt_login_v1_auth_jwt_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_auth_jwt_login_v1_auth_jwt_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_jwt_logout_v1_auth_jwt_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register_register_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_request_token_v1_auth_request_verify_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_verify_request_token_v1_auth_request_verify_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_reset_password_v1_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_reset_reset_password_v1_auth_reset_password_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_verify_v1_auth_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_verify_verify_v1_auth_verify_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invoice_v1_billing_invoice_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    receive_ipn_v1_billing_ipn_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IpnAck"];
                };
            };
        };
    };
    get_cases_v1_cases_get: {
        parameters: {
            query?: {
                /** @description Max number of cases to return. Defaults to settings.cases_top_n_max; max is settings.cases_top_n_max. Must be ≥ 1 (422 on non-positive). 422 if top_n exceeds the configured maximum. */
                top_n?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CasesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unsubscribe_v1_email_unsubscribe_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_feedback_v1_feedback__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_business_metrics_v1_ops_business_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessMetricsResponse"];
                };
            };
        };
    };
    get_packs_v1_packs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackRead"][];
                };
            };
        };
    };
    subscribe_pack_v1_packs__slug__subscribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscribeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unsubscribe_pack_v1_packs__slug__subscribe_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnsubscribeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pool_health_v1_pool_admin_pool_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolHealthResponse"];
                };
            };
        };
    };
    start_qr_login_v1_pool_admin_qr_login_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QRLoginStartResponse"];
                };
            };
        };
    };
    poll_qr_login_v1_pool_admin_qr_login__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QRLoginPollResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_referral_me_v1_referral_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralMeRead"];
                };
            };
        };
    };
    get_trending_v1_trending_get: {
        parameters: {
            query: {
                /** @description Pack slug (e.g. 'crypto-ru'). Must be a known catalog slug. */
                pack: string;
                /** @description Max number of trending items to return. Defaults to settings.trending_top_k_default; max is settings.trending_top_k_max. Must be ≥ 1 (422 on non-positive values). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_users_me_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
        };
    };
    get_delivery_config_v1_users_me_delivery_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryConfigRead"];
                };
            };
        };
    };
    patch_delivery_config_v1_users_me_delivery_config_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeliveryConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryConfigRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_my_tenant_v1_users_me_tenant_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"];
                };
            };
        };
    };
    list_watchlists_v1_watchlists_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_watchlist_v1_watchlists_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_watchlist_v1_watchlists__watchlist_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                watchlist_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_watchlist_v1_watchlists__watchlist_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_watchlist_v1_watchlists__watchlist_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
