/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Account
         * @description Delete the authenticated user and all their data (cascade) -> 204.
         */
        delete: operations["delete_account_account_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Alerts
         * @description List the caller's alerts with pagination and plan-based history window.
         *
         *     Free plan → returns empty list + history_unavailable=True (not 403).
         *     Pro/Team → returns alerts within the plan's history window (30/90 days).
         *     Always tenant-scoped: only the caller's alerts are returned.
         */
        get: operations["list_alerts_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Alert
         * @description Get one alert detail. Foreign or missing alert → 404 (no existence leak).
         */
        get: operations["get_alert_alerts__alert_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oauth:Google.Jwt.Authorize */
        get: operations["oauth_google_jwt_authorize_auth_google_authorize_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Oauth:Google.Jwt.Callback
         * @description The response varies based on the authentication backend used.
         */
        get: operations["oauth_google_jwt_callback_auth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/jwt/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth:Jwt.Login */
        post: operations["auth_jwt_login_auth_jwt_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/jwt/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth:Jwt.Logout */
        post: operations["auth_jwt_logout_auth_jwt_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register:Register */
        post: operations["register_register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/invoice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Invoice
         * @description Create a NOWPayments invoice for the caller's chosen plan/period.
         */
        post: operations["create_invoice_billing_invoice_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/ipn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive Ipn
         * @description Receive a NOWPayments IPN: verify HMAC over the RAW body, then apply.
         */
        post: operations["receive_ipn_billing_ipn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe — returns 200 without touching any backing service.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness: 200 when DB+Redis reachable, else 503 with per-dep markers.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Users Me
         * @description Return the authenticated user's profile.
         *
         *     Behind `current_user` dependency: returns 401 without a valid auth cookie.
         *     Tenant-scoped: only reads data belonging to the requesting user.
         */
        get: operations["get_users_me_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/delivery-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Delivery Config
         * @description Return the authenticated user's delivery configuration (token masked).
         *
         *     `telegram_bot_token` is never returned as the full value — only a masked
         *     representation showing the last 4 characters (or None if not set).
         *     Tenant-scoped: reads only `current_user` data.
         */
        get: operations["get_delivery_config_users_me_delivery_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Delivery Config
         * @description Partial-update the authenticated user's delivery configuration.
         *
         *     - `webhook_url`: requires Pro+ plan (feature-gate → 403 on Free);
         *       SSRF-validated via task-009 guard (private/localhost/non-https → 422).
         *     - `telegram_bot_token`/`telegram_chat_id`: available on all plans.
         *     - Only provided fields are updated (partial PATCH semantics).
         *     - Returns the updated config with the bot token masked.
         */
        patch: operations["patch_delivery_config_users_me_delivery_config_patch"];
        trace?: never;
    };
    "/users/me/tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read My Tenant
         * @description Protected example route (AC2): 401 without a token, tenant id with one.
         */
        get: operations["read_my_tenant_users_me_tenant_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Watchlists
         * @description List only the caller's watchlists (tenant-scoped).
         */
        get: operations["list_watchlists_watchlists_get"];
        put?: never;
        /**
         * Create Watchlist
         * @description Create one watchlist (single channel) for the caller -> 201 WatchlistRead.
         */
        post: operations["create_watchlist_watchlists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlists/{watchlist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Watchlist
         * @description Get one owned watchlist; missing / other tenant's id -> 404.
         */
        get: operations["get_watchlist_watchlists__watchlist_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Watchlist
         * @description Delete an owned watchlist; missing / other tenant's id -> 404.
         */
        delete: operations["delete_watchlist_watchlists__watchlist_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Watchlist
         * @description Partial update of an owned watchlist; missing / other tenant's id -> 404.
         */
        patch: operations["update_watchlist_watchlists__watchlist_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlertConfig
         * @description Per-watchlist alert tuning (maps to Watchlist.threshold/min_channels/lang).
         */
        AlertConfig: {
            /** Min Channels */
            min_channels: number;
            /**
             * Notification Lang
             * @default en
             */
            notification_lang: string;
            /** Score Threshold */
            score_threshold: number;
        };
        /**
         * AlertListResponse
         * @description Paginated list response envelope for GET /alerts.
         *
         *     `history_unavailable` is True when the caller's plan has no history window
         *     (Free plan, HISTORY == 0). The UI must show the plan-upgrade upsell.
         *     The plan window is enforced backend-side; the frontend MUST NOT hard-code
         *     the 30/90 day numbers inline (TASK-016 invariant: backend is source of truth).
         */
        AlertListResponse: {
            /** History Unavailable */
            history_unavailable: boolean;
            /** Items */
            items: components["schemas"]["AlertRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * AlertRead
         * @description Read-only projection of one alert row (with Cluster.topic join).
         */
        AlertRead: {
            /** Channels Count */
            channels_count: number;
            /** Delivery Status */
            delivery_status: string;
            /**
             * First Seen
             * Format: date-time
             */
            first_seen: string;
            /** Id */
            id: number;
            /** Score */
            score: number;
            /** Topic */
            topic: string;
        };
        /**
         * BillingPeriod
         * @description Billing period for an invoice. Crypto has no native subscriptions, so the
         *     only supported period is a calendar month; the duration lives in `PERIOD_DAYS`.
         * @enum {string}
         */
        BillingPeriod: "month";
        /** Body_auth_jwt_login_auth_jwt_login_post */
        Body_auth_jwt_login_auth_jwt_login_post: {
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
            /** Grant Type */
            grant_type?: string | null;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Username */
            username: string;
        };
        /**
         * ChannelRef
         * @description A single source reference: a platform `kind` + its `handle` (ADR-001).
         */
        ChannelRef: {
            /** Handle */
            handle: string;
            /** @default telegram */
            kind: components["schemas"]["SourceKind"];
        };
        /**
         * DeliveryConfigRead
         * @description Read projection of the user's delivery configuration.
         *
         *     `telegram_bot_token_masked` is None if not set, or a masked string
         *     (e.g. ``***gh1``) if set. The full token is NEVER included.
         */
        DeliveryConfigRead: {
            /** Telegram Bot Token Masked */
            telegram_bot_token_masked: string | null;
            /** Telegram Chat Id */
            telegram_chat_id: string | null;
            /** Webhook Url */
            webhook_url: string | null;
        };
        /**
         * DeliveryConfigUpdate
         * @description Partial-update body for PATCH /users/me/delivery-config.
         *
         *     All fields are optional; only provided fields are updated.
         *     `webhook_url` must pass the server-side SSRF guard (task-009) and the
         *     Pro+ feature-gate check before persisting.
         */
        DeliveryConfigUpdate: {
            /** Telegram Bot Token */
            telegram_bot_token?: string | null;
            /** Telegram Chat Id */
            telegram_chat_id?: string | null;
            /** Webhook Url */
            webhook_url?: string | null;
        };
        /** ErrorModel */
        ErrorModel: {
            /** Detail */
            detail: string | {
                [key: string]: string;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness payload returned by `GET /health`.
         */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * InvoiceRequest
         * @description Create-invoice request body (validated at the boundary).
         */
        InvoiceRequest: {
            /** @default month */
            period: components["schemas"]["BillingPeriod"];
            plan: components["schemas"]["Plan"];
        };
        /**
         * InvoiceResponse
         * @description Invoice response: where to pay + the order id to reconcile the IPN.
         */
        InvoiceResponse: {
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
            /** Order Id */
            order_id: string;
            /** Payment Url */
            payment_url: string;
            /** Redirect Url */
            redirect_url: string | null;
        };
        /**
         * IpnAck
         * @description Ack body returned for any handled IPN (200).
         */
        IpnAck: {
            /** Status */
            status: string;
        };
        /** OAuth2AuthorizeResponse */
        OAuth2AuthorizeResponse: {
            /** Authorization Url */
            authorization_url: string;
        };
        /**
         * Plan
         * @description Subscription tiers (overview §6). String values match `users.plan`.
         * @enum {string}
         */
        Plan: "free" | "pro" | "team";
        /**
         * SourceKind
         * @description Platform a channel belongs to. Telegram now; Twitter/X later (ADR-001).
         * @enum {string}
         */
        SourceKind: "telegram";
        /**
         * TenantResponse
         * @description Tenant identity payload for the protected example route.
         */
        TenantResponse: {
            /** User Id */
            user_id: number;
        };
        /**
         * UserCreate
         * @description Registration payload (email + password, validated by the library).
         */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean | null;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean | null;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean | null;
            /** Password */
            password: string;
        };
        /**
         * UserMeResponse
         * @description Public current-user payload (read-only, no secrets).
         */
        UserMeResponse: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Id */
            id: number;
            /** Is Verified */
            is_verified: boolean;
            /** Plan */
            plan: string;
        };
        /**
         * UserRead
         * @description Public user representation returned by register / users routes.
         */
        UserRead: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Id */
            id: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WatchlistCreate
         * @description Create payload: one topic + one channel + alert-config -> one watchlist row.
         */
        WatchlistCreate: {
            alert_config: components["schemas"]["AlertConfig"];
            channel: components["schemas"]["ChannelRef"];
            /** Topic */
            topic: string;
        };
        /**
         * WatchlistRead
         * @description Response model: the persisted watchlist row, tenant id included (AC1).
         */
        WatchlistRead: {
            alert_config: components["schemas"]["AlertConfig"];
            channel: components["schemas"]["ChannelRef"];
            /** Id */
            id: number;
            /** Topic */
            topic: string;
            /** User Id */
            user_id: number;
        };
        /**
         * WatchlistUpdate
         * @description Partial update: only supplied fields are applied (PATCH, `exclude_unset`).
         */
        WatchlistUpdate: {
            alert_config?: components["schemas"]["AlertConfig"] | null;
            channel?: components["schemas"]["ChannelRef"] | null;
            /** Topic */
            topic?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    delete_account_account_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_alerts_alerts_get: {
        parameters: {
            query?: {
                /** @description Maximum number of alerts to return (server silently clamps to max). */
                limit?: number;
                /** @description Number of alerts to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alert_alerts__alert_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_google_jwt_authorize_auth_google_authorize_get: {
        parameters: {
            query?: {
                scopes?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuth2AuthorizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_google_jwt_callback_auth_google_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                code_verifier?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_jwt_login_auth_jwt_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_auth_jwt_login_auth_jwt_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_jwt_logout_auth_jwt_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register_register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invoice_billing_invoice_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    receive_ipn_billing_ipn_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IpnAck"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_users_me_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
        };
    };
    get_delivery_config_users_me_delivery_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryConfigRead"];
                };
            };
        };
    };
    patch_delivery_config_users_me_delivery_config_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeliveryConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryConfigRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_my_tenant_users_me_tenant_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"];
                };
            };
        };
    };
    list_watchlists_watchlists_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistRead"][];
                };
            };
        };
    };
    create_watchlist_watchlists_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_watchlist_watchlists__watchlist_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_watchlist_watchlists__watchlist_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_watchlist_watchlists__watchlist_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
