#!/usr/bin/env sh
# ansible-unpack.sh — materialize development/env/{deploy.env,sensitive.env}
# from ops/ansible/group_vars/{all.yml,vault.yml}.
#
# TASK-001 STUB: dependency-free (no ansible/ansible-vault/yq). It parses the flat
# `key: value` YAML in group_vars and renders KEY=value env files. task-012
# replaces this with real `ansible-vault` decryption (ADR-005 §4).
#
# - deploy.env  ← group_vars/all.yml   (non-secret; committed copy is overwritten)
# - sensitive.env ← group_vars/vault.yml (secrets; gitignored)
set -eu

# Repo root = two levels up from this script (development/scripts/ -> apps/trendPulse).
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ROOT=$(CDPATH= cd -- "${SCRIPT_DIR}/../.." && pwd)

ALL_YML="${ROOT}/ops/ansible/group_vars/all.yml"
VAULT_YML="${ROOT}/ops/ansible/group_vars/vault.yml"
ENV_DIR="${ROOT}/development/env"
DEPLOY_ENV="${ENV_DIR}/deploy.env"
SENSITIVE_ENV="${ENV_DIR}/sensitive.env"

mkdir -p "${ENV_DIR}"

# render_env <source-yaml> <dest-env> <header-comment>
# Converts flat `key: value` YAML lines to UPPERCASE_KEY=value, stripping
# YAML comments, the `---` doc marker, and surrounding quotes on values.
render_env() {
    src="$1"
    dest="$2"
    header="$3"
    if [ ! -f "${src}" ]; then
        echo "ansible-unpack: missing ${src}" >&2
        exit 1
    fi
    {
        printf '# %s\n' "${header}"
        printf '# Generated by development/scripts/ansible-unpack.sh — DO NOT edit by hand.\n'
        awk '
            /^[[:space:]]*#/ { next }            # comment line
            /^---[[:space:]]*$/ { next }          # yaml doc marker
            /^[[:space:]]*$/ { next }             # blank line
            /^[A-Za-z0-9_]+[[:space:]]*:/ {
                key = $0
                sub(/[[:space:]]*:.*$/, "", key)            # key before colon
                val = $0
                sub(/^[^:]*:[[:space:]]*/, "", val)         # value after colon
                sub(/[[:space:]]+#.*$/, "", val)            # trailing inline comment
                gsub(/^"|"$/, "", val)                      # strip double quotes
                gsub(/^'"'"'|'"'"'$/, "", val)              # strip single quotes
                ukey = toupper(key)
                printf "%s=%s\n", ukey, val
            }
        ' "${src}"
    } > "${dest}"
    echo "ansible-unpack: wrote ${dest}"
}

render_env "${ALL_YML}" "${DEPLOY_ENV}" "deploy.env (non-secret) — rendered from ops/ansible/group_vars/all.yml"
render_env "${VAULT_YML}" "${SENSITIVE_ENV}" "sensitive.env (SECRETS, gitignored) — rendered from ops/ansible/group_vars/vault.yml"

chmod 600 "${SENSITIVE_ENV}"
echo "ansible-unpack: done"
